jwt:
  secretKey: SGVsbG8gV29ybGQhsdfawefasdfawefsafwefasdfqwf1f1f12f1zfsadfazvzxbjyiytu

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh
oauth:
  kakao:
    client_id: 697cc76de5e8728806770500967d2284
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    client_id: 8hkZfVL64Rn0ES106NYU
    client_secret : u69M3gs_1K
    redirect_uri : http://localhost:3000/otoo_react/naverLogin
  google:
    client_id: 750077853896-rc6oo0md5bae842jv00ddj1agk0vvqlt.apps.googleusercontent.com
    client_secret: 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
    redirect_uri: http://localhost:3000/otoo_react/googleLogin

data:
  redis:
    port: 6379
    host: localhost


spring:
  application:
    name: otoo_java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/otoo_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: otoo
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.naver.com
    port: 587
    username: gustjrl9208
    password: qwer1234*0
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.naver.com

fast:
  url: http://localhost:8000/process

fastapi:
  url: http://localhost:8001/conflict


